version: '3'
services:
    server_wp:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./_docker/nginx/log:/var/log/nginx
        ports:
            - "8080:80"
        container_name: server_wp
        depends_on:
            - wordpress
    wordpress:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
            - ./_docker/app/wp-config.php:/var/www/wordpress/wp-config.php
        depends_on:
            - db_wp
        container_name: wordpress

    db_wp:
        build:
            context: .
            dockerfile: _docker/app/Dockerfilemysql
        restart: always
        volumes:
            - ./wordpress/tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
            WORDPRESS_ADMIN: ${WORDPRESS_LOGIN}
            WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
            WORDPRESS_MAIL: ${WORDPRESS_MAIL}
        ports:
            - 8191:3306
        container_name: db_wp


    perl:
        image: perl
        volumes:
            - ./db:/data
            - ./_docker/app/perl:/data
        command: [ "perl", "/data/replace_values.pl", "/data/*", "${APP_URL}", '${APP_PATH}' ]
        environment:
            - PERL5LIB=/data

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8381:80"
        links:
            - db_wp:db